name: Toolshop API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman and reporters
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          

      - name: Inject credentials into environment file
        run: |
           node scripts/inject-credentials.js
        env:
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}


      - name: Debug environment after injection
        run: |
          echo "---- ENV FILE ----"
          cat environments/toolshop-ci.json

      - name: Run API tests
        run: npm run test:ci

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-report
          path: reports/results.xml